SELECT 
    p.PRODUCT_CODE AS PRODUCT_CODE, 
    SUM(p.PRICE * o.SALES_AMOUNT) AS SALES
FROM PRODUCT p 
JOIN OFFLINE_SALE o
ON p.PRODUCT_ID = o.PRODUCT_ID
-- 상품코드별(PRODUCT_CODE)로 묶기
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC