-- DATE_FORMAT : 날짜 표현식 
SELECT 
  DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
  PRODUCT_ID,
  USER_ID,
  SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

-- 오프라인과 온라인 전부 SELECT 하기 위해 UNION ALL 사용
UNION ALL

SELECT 
  DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
  PRODUCT_ID,
  NULL AS USER_ID,  -- OFFLINE_SALE는 USER_ID가 없기 때문에 NULL 처리
  SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

-- 판매일 기준으로 오름차순
-- 판매일이 같다면 상품 ID를 기준으로 오름차순
-- 상품 ID까지 같다면 유저 ID를 기준으로 오름차순
ORDER BY 
  SALES_DATE ASC, 
  PRODUCT_ID ASC, 
  USER_ID ASC;