-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CRAETED_DATE
FROM USED_GOODS_BOARD b INNER JOIN USED_GOODS_REPLY r on b.BOARD_ID = r.BOARD_ID
WHERE b.CREATED_DATE LIKE '2022-10%'
-- WHERE MONTH(B.CREATED_DATE) = 10
-- WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
-- WHERE SUBSTR(B.CREATED_DATE,1,7) = '2022-10'
-- WHERE B.CREATED_DATE BETWEEN ('2022-10-01') AND ('2022-10-31')
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC
